# Generated by Django 4.2.13 on 2024-06-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='title',
            field=models.CharField(default='a', max_length=255, verbose_name='title'),
            preserve_default=False,
        ),
    ]
