# Generated by Django 4.2.13 on 2024-06-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_discount_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('send_private_email', 'Can send private email to user by the button')], 'verbose_name': 'customer', 'verbose_name_plural': 'customers'},
        ),
    ]
