
services:
  web:
    build: .
    container_name: store-api
    command: python /code/manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/code
    ports:
      - 8000:8000
    

  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust" # just for development
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"


volumes:  
  db_data: {}
